### ISSUE TITLE
Version 1.0.11 introduced a bug in the usfm output formatting.

### ISSUE THREAD

**Issue by neutrinog** [translationCoreApps/usfm-js#49]
It will take some input like 

```usfm
\id REV unfoldingWord Literal Text
\ide UTF-8
\h Revelation
\toc1 The Book of Revelation
\toc2 Revelation
\toc3 Rev
\mt Revelation

\s5
\c 1
\p
\v 1
\zaln-s | x-content="Βίβλος"
\w book\w*
\zaln-e\*
\zaln-s | x-content="γενέσεως"
\w genealogy\w*
\zaln-e\*
\zaln-s | x-content="Ἰησοῦ"
\w Jesus\w*
\zaln-e\*
\zaln-s | x-content="Χριστοῦ"
\w Christ\w*
\zaln-e\*
\zaln-s | x-content="υἱοῦ"
\w son\w*
\w of\w*
\zaln-e\*
```

and turn it into

```usfm
\id REV unfoldingWord Literal Text
\ide UTF-8
\h Revelation
\toc1 The Book of Revelation
\toc2 Revelation
\toc3 Rev
\mt Revelation

\s5
\c 1
\p
\v 1 \zaln-s | x-content="Βίβλος"
\w book\w*
\zaln-e\*
\zaln-s | x-content="γενέσεως"
\w genealogy\w*
\zaln-e\*
\zaln-s | x-content="Ἰησοῦ"
\w Jesus\w*
\zaln-e\*
\zaln-s | x-content="Χριστοῦ"
\w Christ\w*
\zaln-e\*
\zaln-s | x-content="υἱοῦ"
\w son\w*\w of\w*
\zaln-e\*
```

Note some of the lines have been combined together.

Try this:
```js
let jsonForm = usfm.toJSON(inputusfm);
let badOutput = usfm.toUSFM(jsonForm);
```

**Comment by neutrinog** [comment]
looks like it may have been a result of https://github.com/translationCoreApps/usfm-js/pull/48

**Comment by PhotoNomad0** [comment]
@neutrinog - Can you add steps to reproduce?  Note that adding alignments on USFM output are handled in word-aligner & tCore so it may not necessarily be a problem in usfm-js.

**Comment by neutrinog** [comment]
updated description.

**Comment by PhotoNomad0** [comment]
Will take a look.  The complication is that user requirements were to force a new line before each word and alignment tag for readability, but that is adding white space that isn’t part of the text.  On import those new lines are removed for text readability.  But now there is a flag for outputting USFM with or without the forced newlines.  without for when we save the verse text internally and with force newlines for output to file system.  Thinking that is the issue.  Will test with your example to make sure.

**Comment by PhotoNomad0** [comment]
I think this is resolved with recommendation above.
