### ISSUE TITLE
Incorrect whitespace normalization

### ISSUE THREAD

**Issue by AndyHubert** [translationCoreApps/usfm-js#50]
I am using version 1.0.11.

The following sample code from Gen 1:2 of the UHB (corrected to have words connected by ־ on the same line) is parsed to JSON without any spaces indicated between the words.

```
\w וְ​הָ​אָ֗רֶץ|lemma="אֶרֶץ" strong="c:d:H0776" x-morph="He,C:Td:Ncbsa" \w*
\w הָיְתָ֥ה|lemma="הָיָה" strong="H1961" x-morph="He,Vqp3fs" \w*
\w תֹ֨הוּ֙|lemma="תֹּהוּ" strong="H8414" x-morph="He,Ncmsa" \w*
\w וָ​בֹ֔הוּ|lemma="בֹּהוּ" strong="c:H0922" x-morph="He,C:Ncmsa" \w*
\w וְ​חֹ֖שֶׁךְ|lemma="חֹשֶׁךְ" strong="c:H2822" x-morph="He,C:Ncmsa" \w*
\w עַל|lemma="עַל" strong="H5921a" x-morph="He,R" \w*־\w פְּנֵ֣י|lemma="פָּנִים" strong="H6440" x-morph="He,Ncbpc" \w*
\w תְה֑וֹם|lemma="תְּהוֹם" strong="H8415" x-morph="He,Ncbsa" \w*
\w וְ​ר֣וּחַ|lemma="רוּחַ" strong="c:H7307" x-morph="He,C:Ncbsc" \w*
\w אֱלֹהִ֔ים|lemma="אֱלֹהִים" strong="H0430" x-morph="He,Ncmpa" \w*
\w מְרַחֶ֖פֶת|lemma="רָחַף" strong="H7363b" x-morph="He,Vprfsa" \w*
\w עַל|lemma="עַל" strong="H5921a" x-morph="He,R" \w*־\w פְּנֵ֥י|lemma="פָּנִים" strong="H6440" x-morph="He,Ncbpc" \w*
\w הַ​מָּֽיִם|lemma="מַיִם" strong="d:H4325" x-morph="He,Td:Ncmpa" \w*׃
```

It produces:

```
[
  {
    "text": "וְ​הָ​אָ֗רֶץ",
    "tag": "w",
    "type": "word",
    "lemma": "אֶרֶץ",
    "strong": "c:d:H0776",
    "morph": "He,C:Td:Ncbsa"
  },
  {
    "text": "הָיְתָ֥ה",
    "tag": "w",
    "type": "word",
    "lemma": "הָיָה",
    "strong": "H1961",
    "morph": "He,Vqp3fs"
  },
  {
    "text": "תֹ֨הוּ֙",
    "tag": "w",
    "type": "word",
    "lemma": "תֹּהוּ",
    "strong": "H8414",
    "morph": "He,Ncmsa"
  },
  {
    "text": "וָ​בֹ֔הוּ",
    "tag": "w",
    "type": "word",
    "lemma": "בֹּהוּ",
    "strong": "c:H0922",
    "morph": "He,C:Ncmsa"
  },
  {
    "text": "וְ​חֹ֖שֶׁךְ",
    "tag": "w",
    "type": "word",
    "lemma": "חֹשֶׁךְ",
    "strong": "c:H2822",
    "morph": "He,C:Ncmsa"
  },
  {
    "text": "עַל",
    "tag": "w",
    "type": "word",
    "lemma": "עַל",
    "strong": "H5921a",
    "morph": "He,R"
  },
  {
    "type": "text",
    "text": "־"
  },
  {
    "text": "פְּנֵ֣י",
    "tag": "w",
    "type": "word",
    "lemma": "פָּנִים",
    "strong": "H6440",
    "morph": "He,Ncbpc"
  },
  ...
  {
    "text": "הַ​מָּֽיִם",
    "tag": "w",
    "type": "word",
    "lemma": "מַיִם",
    "strong": "d:H4325",
    "morph": "He,Td:Ncmpa"
  },
  {
    "type": "text",
    "text": "׃\n"
  }
]
```

According to the second point [here](https://ubsicap.github.io/usfm/about/syntax.html?highlight=whitespace#whitespace-normalization) in the USFM specification, each newline should be normalized to a single space. Thus, I would expect:

```
[
  {
    "text": "וְ​הָ​אָ֗רֶץ",
    "tag": "w",
    "type": "word",
    "lemma": "אֶרֶץ",
    "strong": "c:d:H0776",
    "morph": "He,C:Td:Ncbsa"
  },
  {
    "type": "text",
    "text": " "
  },
  {
    "text": "הָיְתָ֥ה",
    "tag": "w",
    "type": "word",
    "lemma": "הָיָה",
    "strong": "H1961",
    "morph": "He,Vqp3fs"
  },
  {
    "type": "text",
    "text": " "
  },
  {
    "text": "תֹ֨הוּ֙",
    "tag": "w",
    "type": "word",
    "lemma": "תֹּהוּ",
    "strong": "H8414",
    "morph": "He,Ncmsa"
  },
  {
    "type": "text",
    "text": " "
  },
  {
    "text": "וָ​בֹ֔הוּ",
    "tag": "w",
    "type": "word",
    "lemma": "בֹּהוּ",
    "strong": "c:H0922",
    "morph": "He,C:Ncmsa"
  },
  {
    "type": "text",
    "text": " "
  },
  {
    "text": "וְ​חֹ֖שֶׁךְ",
    "tag": "w",
    "type": "word",
    "lemma": "חֹשֶׁךְ",
    "strong": "c:H2822",
    "morph": "He,C:Ncmsa"
  },
  {
    "type": "text",
    "text": " "
  },
  {
    "text": "עַל",
    "tag": "w",
    "type": "word",
    "lemma": "עַל",
    "strong": "H5921a",
    "morph": "He,R"
  },
  {
    "type": "text",
    "text": "־"
  },
  {
    "text": "פְּנֵ֣י",
    "tag": "w",
    "type": "word",
    "lemma": "פָּנִים",
    "strong": "H6440",
    "morph": "He,Ncbpc"
  },
  ...
  {
    "text": "הַ​מָּֽיִם",
    "tag": "w",
    "type": "word",
    "lemma": "מַיִם",
    "strong": "d:H4325",
    "morph": "He,Td:Ncmpa"
  },
  {
    "type": "text",
    "text": "׃\n"
  }
]
```

**Comment by AndyHubert** [comment]
In addition, whitespace normalization after an end tag is also incorrect—at least per my understanding. Take this contrived example:

```
In the beginning G\\sc od\\sc* created.
```

Presently, it produces:
```json
[
  {
    "type": "text",
    "text": "In the beginning G"
  },
  {
    "tag": "sc",
    "text": "od",
    "endTag": "sc*",
    "nextChar": " "
  },
  {
    "type": "text",
    "text": "created."
  }
]
```

While it does include the "nextChar" key, I believe it ought also (or instead) to include a text space. That is, `"created."` should begin with a space.

**Comment by PhotoNomad0** [comment]
I agree there is a deficiency here.  It seems there needs to be some work on inline marker support.  Also the nextChar was added in case of ease in rendering only translatable text (without USFM markers) for ease in translation checking.  It should not be used for inline markers.

**Comment by PhotoNomad0** [comment]
Should be partially addressed in version 1.0.12:
- Issue fixed where nextChar contained part of text for inline USFM markers.

Not addressed having spaces in the json between words.  This is handled on json to USFM conversion with two use cases:
- with forcedNewLines true, the `\w` markers will be at start of line.
- otherwise the `\w` markers will be inline with text and space added between adjacent words if needed.

**Comment by AndyHubert** [comment]
Perhaps I am misunderstanding you, but the issue that remains is that, in this implementation, there is no way to know if there ought to be a space between words or not. For Hebrew, this is relevant when there is a maqqef, and in a few other instances (eg. "אביעד" in Isaiah 9) when there are two words joined together without a space.

Eg. "עַל־פְּנֵ֣י תְּהוֹם"

```
\w עַל|lemma="עַל" strong="H5921a" x-morph="He,R" \w*־\w פְּנֵ֣י|lemma="פָּנִים" strong="H6440" x-morph="He,Ncbpc" \w*
\w תְה֑וֹם|lemma="תְּהוֹם" strong="H8415" x-morph="He,Ncbsa" \w*
```

By having "עַל" and "פְּנֵ֣י" on the same line in the usfm (with the maqqef between), we indicate that there should not be a space between these two. However, the fact that "תְּהוֹם" is on a new line shows there should be a space before it. But this distinction is lost when it becomes a js object in the current implementation.

**Comment by PhotoNomad0** [comment]
@AndyHubert -  No, it looks like I misunderstood the point here.  Seeking some advice how to handle this in our app.

@jag3773 @klappy - any ideas how we should address this?  Our current implementation seems to more Greek focused where we always presume some white space between words.  Currently we have two use cases in our app:
- when we import USFM with our original language alignments - the word objects have attributes removed and added back later when we export with alignments.
- importing existing books that have word markers and we try to preserve everything as is.

Not sure we would handle Hebrew well with forced newlines before each word.
