### ISSUE TITLE
Nesting not fully supported

### ISSUE THREAD

**Issue by AndyHubert** [translationCoreApps/usfm-js#51]
I am using version 1.0.11.

I have tested the inclusion of the \nd marker in nesting, as presented as an example in the docs. This works properly. However, other markers do not work when nested. Eg. \sc, \it.

[USFM docs on nesting](http://ubsicap.github.io/usfm/characters/nesting.html)

**Comment by PhotoNomad0** [comment]
Should be fixed in version 1.0.12

**Comment by AndyHubert** [comment]
Great!
